---
root: true

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project:
    - ./**/tsconfig.json

env:
  node: true
  browser: true
  es6: true

plugins:
  - '@typescript-eslint'
  - react-hooks

extends:
  - standard-with-typescript

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

  node/handle-callback-err: off
  node/no-callback-literal: off

  comma-dangle:
    - error
    - only-multiline
  indent: off
  multiline-ternary: off
  no-case-declarations: off
  no-fallthrough: off
  no-return-await: off
  no-template-curly-in-string: off
  no-useless-escape: off
  prefer-promise-reject-errors: off
  prefer-optional-chain: off
  semi: off
  space-before-function-paren: off
  spaced-comment: off
  symbol-description: off

overrides:
  - files:
      - '*.ts'
      - '*.tsx'
    extends:
      - plugin:@typescript-eslint/recommended
      - plugin:@typescript-eslint/recommended-requiring-type-checking
    parserOptions:
      project:
        - ./tsconfig.json
    rules:
      '@typescript-eslint/comma-dangle': off
      '@typescript-eslint/strict-boolean-expressions': off
      '@typescript-eslint/explicit-function-return-type': off
      '@typescript-eslint/no-unused-vars':
        - error
        - args: none
          caughtErrors: none
          ignoreRestSiblings: true
          vars: all
          varsIgnorePattern: ^jsx$
      '@typescript-eslint/indent': off
      '@typescript-eslint/no-dynamic-delete': off
      '@typescript-eslint/no-misused-promises': off
      '@typesript-eslint/prefer-optional-chain': off
      '@typescript-eslint/restrict-template-expressions': off
      '@typescript-eslint/restrict-plus-operands': off
      '@typescript-eslint/no-floating-promises': off
      '@typescript-eslint/no-var-requires': off
      '@typescript-eslint/consistent-type-assertions': off
      '@typescript-eslint/consistent-type-definitions':
        - error
        - type
      '@typescript-eslint/member-delimiter-style': off
      '@typescript-eslint/prefer-optional-chain': off
      '@typescript-eslint/return-await': off
      '@typescript-eslint/no-invalid-void-type': off
      '@typescript-eslint/require-array-sort-compare': off
      '@typescript-eslint/promise-function-async': off
      '@typescript-eslint/semi': off
      '@typescript-eslint/space-before-function-paren':
        - error
        - anonymous: always
          named: never
          asyncArrow: always
