# Use postgres/example user/password credentials

services:
  adminer:
    image: adminer
    ports:
      - 8081:8080

  postgres:
    environment:
      POSTGRES_PASSWORD: example
    image: postgres:14.5
    ports:
      - 5433:5432
    restart: always
    volumes:
      - ./postgres/config:/etc/postgresql:ro
      - ./postgres/log:/var/log/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

version: "3.9"
