# Use postgres/example user/password credentials

services:
  adminer:
    image: adminer
    networks:
      - server_network
    ports:
      - 8080:8080

  postgres:
    environment:
      POSTGRES_PASSWORD: example
    image: postgres:14.5
    networks:
      - bridge_network
      - server_network
    restart: always
    volumes:
      - ./postgres/config:/etc/postgresql:ro
      - ./postgres/log:/var/log/postgresql
      - ./postgres/init:/docker-entrypoint-initdb.d
      - ./postgres/data:/var/lib/postgresql/data

  go:
    build: ./go
    depends_on:
      - postgres
    image: expert-query/go
    networks:
      - server_network
    ports:
      - 3001:3000

  node:
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm start
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
    image: node:18.10
    networks:
      - server_network
    ports:
      - 3000:3000
    user: node
    volumes:
      - ./node:/home/node/app
    working_dir: /home/node/app

networks:
  bridge_network:
    name: bridge_network
  server_network:

version: "3.9"
