# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch    branches: [ develop ]
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    outputs: 
      workflows: ${{ steps.filter.outputs.workflows }}
      app: ${{ steps.filter.outputs.app }}
      etl: ${{ steps.filter.outputs.etl }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it 
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            workflows:
              - '.github/workflows/dev.yml'
            app:
              - 'app/**'
            etl:
              - 'etl/**'
        
  app:
    # Check if this folder has any changes
    needs: changes
    if: ${{ 
      needs.changes.outputs.app == 'true' ||  
      needs.changes.outputs.workflows == 'true' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Set environment variables
    env:
      APP_NAME: expert-query-dev
      CLOUD_SPACE: dev

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: echo "app changed"

  etl:
    # Check if this folder has any changes
    needs: changes
    if: ${{ 
        needs.changes.outputs.etl == 'true' ||  
        needs.changes.outputs.workflows == 'true' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: dev

    # Set environment variables
    env:
      APP_NAME: expert-query-etl-dev
      CLOUD_SPACE: dev

    steps:
      - uses: actions/checkout@v2
      - run: echo "etl changed"
